import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Notification from "@/src/components/notification";
import Navbar from "@/src/components/navbar";
import Footer from "@/src/components/footer";
import { CartProvider } from "../src/context/CartContext";
import CartModal from "../src/components/CartModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Foodlivery",  
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased no-scrollbar`}
      > <Notification/>
        <CartProvider>
          <Navbar/>
          {children}
          <Footer/>
          <CartModal />
        </CartProvider>
      </body>
    </html>
  );
}
